### ISSUE TITLE
Proofreading

### ISSUE THREAD

**Issue by SThomasP** [sourcebots/docs#1]
Proofread and leave mistakes in the replies to this issue please.

**Comment by RealOrangeOne** [comment]
Closed in #2

**Comment by SThomasP** [comment]
Reopening as you can never do too much proofreading

**Comment by Adimote** [comment]
See my issues #4 #5 #6 #7 #8 #9 #10 #11 #12 #13

**Comment by RealOrangeOne** [comment]
Closing. Site has changed, and we can assume proof-reading is always required.
