### ISSUE TITLE
Directory name /static/docs is confusing

### ISSUE THREAD

**Issue by trickeydan** [sourcebots/docs#108]
This directory name is not very clear as to what it contains.

I wouldn't have said that a pdf of markers is a document.

Perhaps /static/downloads/ or /static/pdf/

**Comment by RealOrangeOne** [comment]
Agreed. I'm planning to do an overhaul of the static assets for the docs very soon, which will reduce the generic content in here.

**Comment by trickeydan** [comment]
Any update on the progress of this @RealOrangeOne ?

**Comment by RealOrangeOne** [comment]
It's not been done yet, but I might spend tonight doing it if nothing more urgent needs doing.
