### ISSUE TITLE
Misleading exercise in "Average calculator" section of Whirlwind Tour

### ISSUE THREAD

**Issue by kierdavis** [sourcebots/docs#119]
The text says something like "input is like input", which makes no sense. Additionally it doesn't make it clear that the return value of `input` needs converting from a string to an integer or float using `int`/`float`.

The paragraph could probably do with being rewritten.

Spun from #116.

**Comment by RealOrangeOne** [comment]
Sounds like I changed raw_input without checking the surrounding sentence, woops!

**Comment by tpoomlmly** [comment]
The whirlwind tour has been replaced with a newer, windier one without an "Average calculator" section
