### ISSUE TITLE
Discussion point: Whirlwind Tour solutions

### ISSUE THREAD

**Issue by kierdavis** [sourcebots/docs#120]
We should consider if we're going to provide solutions to the exercises in the Whirlwind Tour Python tutorial.

I think putting solutions directly on the website would make it too each for people to just look at the answers and not learn anything. Perhaps we could mention that we can provide hints and/or improvements to thuteir solutions by email?

Spun out from #116.

**Comment by antonnikitin97** [comment]
Hmm... I think providing a sort of very general "this is the output you should expect to get" and nothing else is good enough and then like you said, suggesting they contact us for hints/tips...

**Comment by tpoomlmly** [comment]
The whirlwind tour has been rewhirled, making this issue a non-issue
