### ISSUE TITLE
Needs instructions on how to use Webots

### ISSUE THREAD

**Issue by tpoomlmly** [sourcebots/docs#154]
We can probably copy this from https://github.com/srobo/docs

**Comment by jefftheprogrammer** [comment]
Ok, it will mostly close it. It seems the read-me page for the simulator is quite descriptive. We can use it for the docs https://github.com/sourcebots/competition-simulator

**Comment by RealOrangeOne** [comment]
Should this issue also have in scope a tutorial for how they'll interact with the simulator runner to run simulations and get logs? https://github.com/RealOrangeOne/simulator-runner/ (README explains a bit more).
