### ISSUE TITLE
Replace the whirlwind tour's contents with the training booklet

### ISSUE THREAD

**Issue by tpoomlmly** [sourcebots/docs#157]
Should we replace the current whirlwind tour with the tutorial we made for the [booklet](https://docs.google.com/document/d/1EU5jBCifyXEjuW4HrQe1XJ7g_LoEmx3dcvxTEpoPr0k/edit)?

It's trivial to port it to markdown, and it's made with content we're all satisfied with in regards to what's being taught, order etc.

**Comment by RealOrangeOne** [comment]
Yeah that sounds like a good idea - no point duplicating content!

**Comment by jefftheprogrammer** [comment]
Fairs. Will do so now.
