### ISSUE TITLE
Broken links on robot page

### ISSUE THREAD

**Issue by tpoomlmly** [sourcebots/docs#184]
The links to the robots on the [robot page](https://docs.sourcebots.co.uk/robots) are broken

**Comment by tpoomlmly** [comment]
This doesn't happen anymore for some reason

**Comment by PeterJCLaw** [comment]
This happens because the links are spelled wrongly, but the bug only surfaces when there isn't a trailing slash in the url. Visiting https://docs.sourcebots.co.uk/robots rather than https://docs.sourcebots.co.uk/robots/ reproduces this.
