### ISSUE TITLE
reference.md is a bit too technical

### ISSUE THREAD

**Issue by Adimote** [sourcebots/docs#3]
There are a few things which are slightly too technical for people who might be new to code, specific things are:

- [ ] The headers of each section probably should include a very quick description of how to access them, as they'll never really know the objects by their class name. (try not to repeat yourself though, just summarise the fastest way to get one)

- [ ] Avoid the use of the word 'Dictionary', I'd consider that advanced python. Just pretend the different boards are lists of boards, which can also be indexed by serial number if needed.

**Comment by RealOrangeOne** [comment]
`references.md` to be replaced with sphinx build from `robot-api`
