### ISSUE TITLE
Change all names of a Robot instance to `r`

### ISSUE THREAD

**Issue by Adimote** [sourcebots/docs#9]
I notice lots of examples use
```python
from robot import Robot
robot = Robot()
robot.motor_board.m0 = robot.BRAKE
```
This would actually be invalid, because the last robot is now referencing the Robot instance, not the package name. We need to change everything to use r instead of robot in this case. IE:
```python
from robot import Robot
r = Robot()
r.motor_board.m0 = robot.BRAKE
```
and that'll fix it!

**Comment by RealOrangeOne** [comment]
Your lower example is still invalid, as `robot` will be undefined. `BRAKE` and `COAST` will need to be explicitly imported. 

Either that or we start telling people to `from robot import *`. (**Please not this!**)
